name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/rbcprolabs/epubx.dart
issue_tracker: https://github.com/rbcprolabs/epubx.dart
version: 4.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: 3.3.7
  quiver: 3.2.1
  path: 1.8.3
  xml: 6.3.0
  image: 4.0.17
  collection: 1.17.1

dev_dependencies:
  test: 1.16.7
  pedantic: 1.11.0
